# Generated by Django 5.0.3 on 2024-03-26 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='address1',
            new_name='ship_address1',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='address2',
            new_name='ship_address2',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='city',
            new_name='ship_city',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='country',
            new_name='ship_country',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='email',
            new_name='ship_email',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='full_name',
            new_name='ship_full_name',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='postalcode',
            new_name='ship_postalcode',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='province',
            new_name='ship_province',
        ),
    ]
